### ISSUE TITLE
SDK - getCSVData() fires a TypeError: callback is not a function

### ISSUE THREAD

**Issue by bbouffaut** [partnering/diya-sdk#90]
When calling handler.getCSVData(['Temperature','Ozone'],'2016-01-01 12:12:12', function(data) {} ); the error hereafter is fired. It seems there is a change in the usage of this function.

TypeError: callback is not a function
    at /srv/workspace/diya1-dashboard/node_modules/diya-sdk/src/services/ieq/ieq.js:434:4
    at Object.callback (/srv/workspace/diya1-dashboard/node_modules/diya-sdk/src/DiyaSelector.js:260:39)
    at DiyaNode._notifyListener (/srv/workspace/diya1-dashboard/node_modules/diya-sdk/src/DiyaNode.js:315:12)
    at DiyaNode._handleRequest (/srv/workspace/diya1-dashboard/node_modules/diya-sdk/src/DiyaNode.js:496:8)
    at DiyaNode._onmessage (/srv/workspace/diya1-dashboard/node_modules/diya-sdk/src/DiyaNode.js:364:9)
    at SocketHandler.<anonymous> (/srv/workspace/diya1-dashboard/node_modules/diya-sdk/src/DiyaNode.js:167:47)
    at SocketHandler.EventEmitter.emit (/srv/workspace/diya1-dashboard/node_modules/node-event-emitter/index.js:86:17)
    at SocketHandler._onmessage (/srv/workspace/diya1-dashboard/node_modules/diya-sdk/src/DiyaNode.js:606:8)
    at WebSocket.onMessage (/srv/workspace/diya1-dashboard/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (/srv/workspace/diya1-dashboard/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/srv/workspace/diya1-dashboard/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/srv/workspace/diya1-dashboard/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/srv/workspace/diya1-dashboard/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/srv/workspace/diya1-dashboard/node_modules/ws/lib/Receiver.js:139:10)

**Comment by antoineDeRengerve** [comment]
@bbouffaut You are right, the documentation was not up to date. I changed it, it should be OK now.
