### ISSUE TITLE
Unhandled error fired when WatchIEQRecvErr:"SubscriptionClosed"

### ISSUE THREAD

**Issue by bbouffaut** [partnering/diya-sdk#93]
Periodically, the subscription is closed by peer. It provokes an unhandled error. This is annoying since the program crashes and there is no way to restart by handling the error. Please find details hereafter.

WatchIEQRecvErr:"SubscriptionClosed"
WatchIEQRecvErr:"PeerDisconnected"
/srv/workspace/diya1-data-loader/node_modules/node-event-emitter/index.js:67
throw er; // Unhandled 'error' event
^

Error: Error: unexpected server response (502)
at DiyaNode._onerror (/srv/workspace/diya1-data-loader/node_modules/diya-sdk/src/DiyaNode.js:377:21)
at SocketHandler.<anonymous> (/srv/workspace/diya1-data-loader/node_modules/diya-sdk/src/DiyaNode.js:157:9)
at SocketHandler.EventEmitter.emit (/srv/workspace/diya1-data-loader/node_modules/node-event-emitter/index.js:86:17)
at SocketHandler._onerror (/srv/workspace/diya1-data-loader/node_modules/diya-sdk/src/DiyaNode.js:614:7)
at WebSocket.onError (/srv/workspace/diya1-data-loader/node_modules/ws/lib/EventTarget.js:109:16)
at emitOne (events.js:101:20)
at WebSocket.emit (events.js:188:7)
at ClientRequest._req.on (/srv/workspace/diya1-data-loader/node_modules/ws/lib/WebSocket.js:656:12)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
at TLSSocket.socketOnData (_http_client.js:363:20)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)

**Comment by antoineDeRengerve** [comment]
- You may try to catch 'error' events with the following syntax (sample): 
```
d1("D1R00018").on('error', <callback>)
```

**Comment by antoineDeRengerve** [comment]
By the way, we are investigating why the subscription is periodically closed. This is a new issue on our side.

**Comment by bbouffaut** [comment]
Hi Antoine,

I tried to catch the 'error' with `d1("D1R00018").on('error', <callback>)`

It seems to be better, but a new error appears (Details hereafter).
Looking forward to reading from you.

BR,
Baptiste.

**Details of the error:**
```
WatchIEQRecvErr:"SubscriptionClosed"
WatchIEQRecvErr:"PeerDisconnected"
/srv/workspace/diya1-data-loader/node_modules/diya-sdk/src/DiyaNode.js:538
                        Logger.error("[WS] error : "+JSON.stringify(err));
                                                          ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at WebSocket.<anonymous> (/srv/workspace/diya1-data-loader/node_modules/diya-sdk/src/DiyaNode.js:538:38)
    at WebSocket.onError (/srv/workspace/diya1-data-loader/node_modules/ws/lib/EventTarget.js:109:16)
    at emitOne (events.js:101:20)
    at WebSocket.emit (events.js:188:7)
    at ClientRequest._req.on (/srv/workspace/diya1-data-loader/node_modules/ws/lib/WebSocket.js:656:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)
```

**Comment by antoineDeRengerve** [comment]
Please, update diya-sdk (master). I pushed a patch to avoid this JSON.stringify of a potentially circular structure.

It seems OK when I test, let me know if it solves also your issue.

**Comment by antoineDeRengerve** [comment]
Please, update diya-sdk (master). I pushed a patch to avoid this JSON.stringify of a potentially circular structure.

It seems OK when I test, let me know if it solves also your issue.
